# Generated by Django 3.2.3 on 2021-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdish',
            name='qunatity',
        ),
        migrations.AddField(
            model_name='cartdish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
